# Generated by Django 5.0.6 on 2026-05-16 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='suggested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='suggested_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='suggested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='suggested_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
