# Generated by Django 5.0.6 on 2026-01-10 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa subskrypcji')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('next_payment_date', models.DateField(verbose_name='Data następnej płatności')),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Co miesiąc'), ('YEARLY', 'Co rok')], default='MONTHLY', max_length=10, verbose_name='Częstotliwość')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
