# Generated by Django 5.0.6 on 2026-01-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
